### ISSUE TITLE
 No value transform to serialize field 'event' of type 'GstEvent

### ISSUE THREAD

**Issue by kweisamx** [tik0/mat2gstreamer#1]
Hi @tik0 
I run the command standalone 
```
gst-launch-1.0 -v udpsrc port=5000 caps="application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)RAW, sampling=(string)BGR, depth=(string)8, width=(string)640, height=(string)480" ! rtpvrawdepay ! videoconvert ! ximagesink --gst-debug-level=5
```

but it output error 
```
 No value transform to serialize field 'event' of type 'GstEvent
```
would you have been the question?

Thank you

**Comment by kweisamx** [comment]
The output of binary is 

```
  Video I/O:
    DC1394:                      NO
    FFMPEG:                      NO
      avcodec:                   NO
      avformat:                  NO
      avutil:                    NO
      swscale:                   NO
      avresample:                NO
    GStreamer:                   NO
    libv4l/libv4l2:              NO
    v4l/v4l2:                    linux/videodev2.h
    gPhoto2:                     NO

```

but I actually has install Gstreamer?

**Comment by tik0** [comment]
Hi, I think you are mixing two issues here. For your first message I need more information: Do you run the server command as well: `gst-launch-1.0 -v videotestsrc ! video/x-raw, format=RGB, framerate=25/1, width=640, height=480 ! rtpvrawpay ! udpsink host=localhost port=5000`. What does it do if you disable the debug outputs?

The second issue looks like the output from an OpenCV binary where the library was not built against gstreamer: you either have to install an OpenCV version with gstreamer (like from the [ROS ppa](http://wiki.ros.org/ROS/Installation)), or you build it on your own with the option `WITH_GSTREAMER`.

**Comment by kweisamx** [comment]
OK, Thanks
I will try ,
close
